import { User, Post, MediaItem, Notification, Conversation, Message } from '@/types';

// ===== 模拟用户 =====
export const mockUsers: User[] = [
  {
    id: 'u1',
    email: 'xuxiake@example.com',
    username: 'xuxiake',
    displayName: '徐霞客',
    bio: '带着VR眼镜看世界 🌍 记录每一段旅程',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=xuxiake',
    vrDeviceInfo: { model: 'Apple Vision Pro', version: '2.0' },
    website: 'https://xuxiake.com',
    createdAt: '2025-01-15T08:00:00Z',
  },
  {
    id: 'u2',
    email: 'zhangshan@example.com',
    username: 'zhangshan',
    displayName: '张三',
    bio: 'VR摄影师 | 旅行爱好者',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=zhangshan',
    createdAt: '2025-02-20T10:30:00Z',
  },
  {
    id: 'u3',
    email: 'lisi@example.com',
    username: 'lisi',
    displayName: '李四',
    bio: '科技评测 | VR内容创作者',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=lisi',
    createdAt: '2025-03-10T14:00:00Z',
  },
  {
    id: 'u4',
    email: 'wangwu@example.com',
    username: 'wangwu',
    displayName: '王五',
    bio: '环球旅行者 🌏 用VR记录世界',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=wangwu',
    createdAt: '2025-04-05T09:15:00Z',
  },
];

// ===== 模拟媒体文件 =====
const mockMediaItems: MediaItem[][] = [
  // Post 1: 黄山 VR 视频 + 图片
  [
    {
      id: 'm1',
      type: 'VIDEO',
      url: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_5MB.mp4',
      thumbnailUrl: 'https://picsum.photos/seed/huangshan1/800/450',
      duration: 120,
      width: 1920,
      height: 1080,
      vrFormat: 'VR360',
      sortOrder: 0,
    },
    {
      id: 'm2',
      type: 'IMAGE',
      url: 'https://picsum.photos/seed/huangshan2/800/600',
      thumbnailUrl: 'https://picsum.photos/seed/huangshan2/400/300',
      width: 800,
      height: 600,
      sortOrder: 1,
    },
    {
      id: 'm3',
      type: 'IMAGE',
      url: 'https://picsum.photos/seed/huangshan3/800/600',
      thumbnailUrl: 'https://picsum.photos/seed/huangshan3/400/300',
      width: 800,
      height: 600,
      sortOrder: 2,
    },
  ],
  // Post 2: 故宫音频 + 翻译
  [
    {
      id: 'm4',
      type: 'AUDIO',
      url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
      thumbnailUrl: null,
      duration: 180,
      sortOrder: 0,
    },
    {
      id: 'm5',
      type: 'TRANSLATION',
      url: '',
      language: 'zh-CN',
      translatedText: '故宫，又称紫禁城，是中国明清两代的皇家宫殿，位于北京中轴线的中心。始建于明成祖永乐四年（1406年），到永乐十八年（1420年）建成。',
      sortOrder: 1,
    },
  ],
  // Post 3: 西湖视频
  [
    {
      id: 'm6',
      type: 'VIDEO',
      url: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_2MB.mp4',
      thumbnailUrl: 'https://picsum.photos/seed/westlake/800/450',
      duration: 90,
      width: 1920,
      height: 1080,
      vrFormat: 'VR180',
      sortOrder: 0,
    },
    {
      id: 'm7',
      type: 'LINK',
      url: '',
      linkUrl: 'https://baike.baidu.com/item/西湖',
      linkTitle: '西湖 - 百度百科',
      linkDescription: '西湖，位于浙江省杭州市西面，是中国大陆首批国家重点风景名胜区之一',
      linkFavicon: 'https://baidu.com/favicon.ico',
      sortOrder: 1,
    },
  ],
  // Post 4: 张家界图片+VR
  [
    {
      id: 'm8',
      type: 'IMAGE',
      url: 'https://picsum.photos/seed/zhangjiajie1/800/600',
      thumbnailUrl: 'https://picsum.photos/seed/zhangjiajie1/400/300',
      width: 800,
      height: 600,
      vrFormat: 'VR360',
      sortOrder: 0,
    },
    {
      id: 'm9',
      type: 'IMAGE',
      url: 'https://picsum.photos/seed/zhangjiajie2/800/600',
      thumbnailUrl: 'https://picsum.photos/seed/zhangjiajie2/400/300',
      width: 800,
      height: 600,
      vrFormat: 'VR360',
      sortOrder: 1,
    },
    {
      id: 'm10',
      type: 'IMAGE',
      url: 'https://picsum.photos/seed/zhangjiajie3/800/600',
      thumbnailUrl: 'https://picsum.photos/seed/zhangjiajie3/400/300',
      width: 800,
      height: 600,
      vrFormat: 'VR360',
      sortOrder: 2,
    },
  ],
  // Post 5: 桂林山水视频+翻译
  [
    {
      id: 'm11',
      type: 'VIDEO',
      url: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_5MB.mp4',
      thumbnailUrl: 'https://picsum.photos/seed/guilin/800/450',
      duration: 150,
      width: 3840,
      height: 2160,
      vrFormat: 'SPATIAL',
      sortOrder: 0,
    },
    {
      id: 'm12',
      type: 'TRANSLATION',
      url: '',
      language: 'en',
      translatedText: 'Guilin landscape is the best under heaven. The Li River winds through the karst mountains, creating a breathtaking natural scenery that has inspired poets and artists for centuries.',
      sortOrder: 1,
    },
  ],
  // Post 6: 长城链接分享
  [
    {
      id: 'm13',
      type: 'IMAGE',
      url: 'https://picsum.photos/seed/greatwall/800/600',
      thumbnailUrl: 'https://picsum.photos/seed/greatwall/400/300',
      width: 800,
      height: 600,
      sortOrder: 0,
    },
    {
      id: 'm14',
      type: 'LINK',
      url: '',
      linkUrl: 'https://baike.baidu.com/item/长城',
      linkTitle: '长城 - 世界文化遗产',
      linkDescription: '长城是中国古代的军事防御工程，是世界文化遗产，也是世界新七大奇迹之一',
      linkFavicon: 'https://baidu.com/favicon.ico',
      sortOrder: 1,
    },
  ],
];

// ===== 模拟帖子 =====
export const mockPosts: Post[] = [
  {
    id: 'p1',
    content: '今天在黄山用VR眼镜拍摄了360度全景视频！云海真的太壮观了，站在光明顶上的感觉就像在仙境一样 🏔️✨',
    mediaItems: mockMediaItems[0],
    author: mockUsers[0],
    location: { lat: 30.1297, lng: 118.1649, name: '黄山风景区' },
    vrMetadata: { device: 'Apple Vision Pro', resolution: '4K', format: 'spatial' },
    visibility: 'PUBLIC',
    likeCount: 128,
    commentCount: 32,
    viewCount: 1520,
    isLiked: false,
    createdAt: '2026-06-23T08:30:00Z',
    updatedAt: '2026-06-23T08:30:00Z',
  },
  {
    id: 'p2',
    content: '故宫博物院一游！用VR眼镜录了一段导游的中文讲解，还自动翻译成了英文版本，外国朋友也能看懂了 🏯',
    mediaItems: mockMediaItems[1],
    author: mockUsers[0],
    location: { lat: 39.9163, lng: 116.3972, name: '故宫博物院' },
    visibility: 'PUBLIC',
    likeCount: 89,
    commentCount: 15,
    viewCount: 980,
    isLiked: true,
    createdAt: '2026-06-22T14:20:00Z',
    updatedAt: '2026-06-22T14:20:00Z',
  },
  {
    id: 'p3',
    content: '杭州西湖太美了！VR180度拍摄断桥残雪，还附上了百度百科链接，方便大家了解更多西湖的历史 🌊',
    mediaItems: mockMediaItems[2],
    author: mockUsers[2],
    location: { lat: 30.2590, lng: 120.1449, name: '杭州西湖' },
    visibility: 'PUBLIC',
    likeCount: 56,
    commentCount: 8,
    viewCount: 720,
    isLiked: false,
    createdAt: '2026-06-21T16:45:00Z',
    updatedAt: '2026-06-21T16:45:00Z',
  },
  {
    id: 'p4',
    content: '张家界国家森林公园！用360度VR全景拍摄，仿佛置身阿凡达世界 🌿🌄',
    mediaItems: mockMediaItems[3],
    author: mockUsers[3],
    location: { lat: 29.3348, lng: 110.4764, name: '张家界国家森林公园' },
    vrMetadata: { device: 'Meta Quest 4', resolution: '8K' },
    visibility: 'PUBLIC',
    likeCount: 203,
    commentCount: 45,
    viewCount: 2890,
    isLiked: false,
    createdAt: '2026-06-20T10:15:00Z',
    updatedAt: '2026-06-20T10:15:00Z',
  },
  {
    id: 'p5',
    content: '桂林山水甲天下！用空间视频记录漓江风光，配合中英文翻译，让全世界的朋友都能感受中国山水之美 🎥',
    mediaItems: mockMediaItems[4],
    author: mockUsers[1],
    location: { lat: 25.2736, lng: 110.2902, name: '桂林漓江' },
    vrMetadata: { device: 'Apple Vision Pro', resolution: '4K' },
    visibility: 'PUBLIC',
    likeCount: 167,
    commentCount: 28,
    viewCount: 2100,
    isLiked: true,
    createdAt: '2026-06-19T09:00:00Z',
    updatedAt: '2026-06-19T09:00:00Z',
  },
  {
    id: 'p6',
    content: '八达岭长城！用VR记录下这段伟大的历史遗迹，并附上了百度百科的详细介绍，快来一起探索长城的历史吧 🏯🇨🇳',
    mediaItems: mockMediaItems[5],
    author: mockUsers[0],
    location: { lat: 40.3597, lng: 116.0201, name: '八达岭长城' },
    visibility: 'PUBLIC',
    likeCount: 94,
    commentCount: 19,
    viewCount: 1350,
    isLiked: false,
    createdAt: '2026-06-18T11:30:00Z',
    updatedAt: '2026-06-18T11:30:00Z',
  },
];

// ===== 模拟通知 =====
export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'LIKE',
    message: '张三 赞了你在黄山的VR视频',
    sender: mockUsers[1],
    postId: 'p1',
    isRead: false,
    createdAt: '2026-06-23T09:15:00Z',
  },
  {
    id: 'n2',
    type: 'COMMENT',
    message: '李四 评论了你在故宫的内容："这个翻译功能太实用了！"',
    sender: mockUsers[2],
    postId: 'p2',
    isRead: false,
    createdAt: '2026-06-22T18:30:00Z',
  },
  {
    id: 'n3',
    type: 'FOLLOW',
    message: '王五 关注了你',
    sender: mockUsers[3],
    isRead: true,
    createdAt: '2026-06-22T12:00:00Z',
  },
  {
    id: 'n4',
    type: 'MESSAGE',
    message: '张三 给你发了一条消息',
    sender: mockUsers[1],
    isRead: false,
    createdAt: '2026-06-23T10:00:00Z',
  },
  {
    id: 'n5',
    type: 'SYSTEM',
    message: '欢迎来到徐霞客系统！开始你的VR旅程吧 🎉',
    isRead: true,
    createdAt: '2026-06-15T08:00:00Z',
  },
];

// ===== 模拟聊天会话 =====
export const mockConversations: Conversation[] = [
  {
    id: 'c1',
    type: 'DIRECT',
    members: [mockUsers[1]],
    lastMessage: {
      id: 'msg1',
      conversationId: 'c1',
      sender: mockUsers[1],
      content: '你拍的黄山VR视频太震撼了！是用什么设备拍的？',
      createdAt: '2026-06-23T10:30:00Z',
    },
    unreadCount: 2,
    updatedAt: '2026-06-23T10:30:00Z',
  },
  {
    id: 'c2',
    type: 'DIRECT',
    members: [mockUsers[2]],
    lastMessage: {
      id: 'msg2',
      conversationId: 'c2',
      sender: mockUsers[0],
      content: '好的，下次一起去桂林拍VR！',
      createdAt: '2026-06-22T15:00:00Z',
    },
    unreadCount: 0,
    updatedAt: '2026-06-22T15:00:00Z',
  },
  {
    id: 'c3',
    type: 'GROUP',
    title: 'VR旅行爱好者群',
    members: [mockUsers[1], mockUsers[2], mockUsers[3]],
    lastMessage: {
      id: 'msg3',
      conversationId: 'c3',
      sender: mockUsers[3],
      content: '推荐一个拍360全景的好地方——九寨沟！',
      createdAt: '2026-06-21T20:00:00Z',
    },
    unreadCount: 5,
    updatedAt: '2026-06-21T20:00:00Z',
  },
];

// ===== 当前登录用户 =====
export const mockCurrentUser: User = mockUsers[0];
